server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tinder_db
    username: ali
    password: alimurad05
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
